name: "build"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
  workflow_call:

  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  default-build:
    strategy:
      matrix:
        image: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.image }}
    name: ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..

      - name: Make
        run: |
          cd build
          make -j2

      - name: Make test
        run: |
          cd build
          make test

      - name: Make install
        run: |
          cd build
          make DESTDIR=../dist install

  minimal-build:
    runs-on: ubuntu-latest
    name: minimal-build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CMake
        run: |
          mkdir build
          cd build
          cmake \
            -DOF_USE_REED_SOLOMON_CODEC=OFF \
            -DOF_USE_REED_SOLOMON_2_M_CODEC=ON \
            -DOF_USE_LDPC_STAIRCASE_CODEC=OFF \
            -DOF_USE_2D_PARITY_MATRIX_CODEC=OFF \
            -DOF_USE_LDPC_FROM_FILE_CODEC=OFF \
            ..

      - name: Make
        run: |
          cd build
          make -j2

      - name: Make test
        run: |
          cd build
          make test

      - name: Make install
        run: |
          cd build
          make DESTDIR=../dist install
