name: "release"

on:
  push:
    tags:
      - v*

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: [build]

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Version
      id: version
      run: |
        echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Debian package
      run: |
        ./scripts/make_deb.sh

    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/libopenfec_${{ steps.version.outputs.GIT_TAG }}_amd64.deb
          dist/libopenfec-dev_${{ steps.version.outputs.GIT_TAG }}_amd64.deb
        name: ${{ steps.version.outputs.GIT_TAG }}
        tag_name: ${{ steps.version.outputs.GIT_TAG }}
        fail_on_unmatched_files: true
        draft: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
